version: '3'

services:
  app:
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile
    # command: yarn start:dev
    volumes:
      - type: bind
        source: ./
        target: /app
    network_mode: "host"
    container_name: portfolio
    ports:
       - ${PORT}:${PORT}
